#+BEGIN_HTML
---
layout: post
title: Lessons from Play!
date: 2010-08-23
categories: 
- 
author: rydnr
excerpt: 
---
#+END_HTML
#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: rydnr
#+DATE: 2010-08-23
#+TITLE: Lessons from Play!
#+DESCRIPTION: 
#+KEYWORDS: 
:PROPERTIES:
:ON: 2010-08-23
:END:
* Lessons from Play!

Hi,

I've started working with <a href="http://www.playframework.org">Play!</a>, and started wondering how much it'd take to follow its (somehow radical) recommendation of not using sessions.
Well, in fact, there're no sessions in Play!. The consequences: you have to use cookies for storing information across requests. So you're tied to 4k per cookie.
The benefits: stateless servers =&gt; scalability boost. They can be added or stopped at will, depending on the traffic. So they are specially suited for cloud hosting.

How much do we use the Session object in webshop? Do the Flash callbacks require session information? If the no-session version of ws is feasible, we could take back the plain old dns balancing instead of staging for installing releases: no need for sticky sessions at apache level.
