#+BEGIN_HTML
---
layout: post
title: microblogging@devblog
date: 2011-03-11
categories: 
- 
author: rydnr
excerpt: 
---
#+END_HTML
#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: rydnr
#+DATE: 2011-03-11
#+TITLE: microblogging@devblog
#+DESCRIPTION: 
#+KEYWORDS: 
:PROPERTIES:
:ON: 2011-03-11
:END:
* microblogging@devblog

May I ask for better support for microblogging?

My 5-minutes research on this topic gives these results:
<ul>
  <li>Wordpress <a href="http://wordpress.org/extend/plugins/tags/microblogging">plugins</a>:
    <ul>
      <li><a href="http://wordpress.org/extend/plugins/wp-admin-microblog/">wp-admin-microblog</a></li>
      <li><a href="http://wordpress.org/extend/plugins/mingle/">Mingle</a></li>
    </ul>
  </li>
  <li><a href="http://status.net/download">StatusNet</a> (<a href="http://identi.ca/">identi.ca</a> engine)</li>
</ul>

I appraise people posting long and detailed entries, and I feel I could be misusing the blog for microblogging. And maybe that could happen to some other people. At least, rcres, bmigu sends me interesting links via jabber regularly, which sometimes I repost here as 'mine' (whatever that means) ;).

So the question is: If we had a private microblogging engine/wp plugin, do you think it would be useful? Otherwise, another option could be sharing a Twitter account, but that means no difference but the lack of privacy...

Either case, I vote +1.
